server:
  port: 8080

spring:
  application:
    name: weather-api
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=1000,expireAfterWrite=30m

weather:
  api:
    base-url: https://api.open-meteo.com/v1/forecast
    timeout: 5000

logging:
  level:
    com.forcasty: DEBUG

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
    tryItOutEnabled: true
  show-actuator: true
